import { Item } from "../../index.js";

export const brickWallItem: Item = {
  name: "Brick Wall",
  type: "block",
  tileType: "wall",
  description: "A sturdy brick wall.",
  level: 0,
  quantity: 0,
  maxQuantity: 64,
  isEquipped: false,
  consumeOnUse: true,
  isMaterial: true,
  canBeCrafted: true,
  canBeUsed: true,
  sellValue: 1,
  buyValue: 2,
  range: 1,
};

export const woodItem: Item = {
  name: "Wood",
  type: "material",
  tileType: "tree",
  description: "A piece of wood from a tree.",
  level: 0,
  quantity: 0,
  maxQuantity: 64,
  isEquipped: false,
  consumeOnUse: true,
  isMaterial: true,
  canBeCrafted: true,
  canBeUsed: true,
  sellValue: 1,
  buyValue: 2,
  range: 1,
};

export const rockItem: Item = {
  name: "Rock",
  type: "block",
  tileType: "rock",
  description: "A small rock.",
  level: 0,
  quantity: 0,
  maxQuantity: 64,
  isEquipped: false,
  consumeOnUse: true,
  isMaterial: true,
  canBeCrafted: true,
  canBeUsed: true,
  sellValue: 1,
  buyValue: 2,
  range: 1,
};

export const grassItem: Item = {
  name: "Grass",
  type: "material",
  tileType: "grass",
  description: "A patch of grass.",
  level: 0,
  quantity: 0,
  maxQuantity: 64,
  isEquipped: false,
  consumeOnUse: true,
  isMaterial: true,
  canBeCrafted: true,
  canBeUsed: true,
  sellValue: 1,
  buyValue: 2,
  range: 1,
};

export const flowerItem: Item = {
  name: "Flower",
  type: "material",
  tileType: "flower",
  description: "A beautiful flower.",
  level: 0,
  quantity: 0,
  maxQuantity: 64,
  isEquipped: false,
  consumeOnUse: true,
  isMaterial: true,
  canBeCrafted: true,
  canBeUsed: true,
  sellValue: 1,
  buyValue: 2,
  range: 1,
};

export const gravelItem: Item = {
  name: "Gravel",
  type: "material",
  tileType: "gravel",
  description: "A patch of gravel.",
  level: 0,
  quantity: 0,
  maxQuantity: 64,
  isEquipped: false,
  consumeOnUse: true,
  isMaterial: true,
  canBeCrafted: true,
  canBeUsed: true,
  sellValue: 1,
  buyValue: 2,
  range: 1,
};

export const dirtItem: Item = {
  name: "Dirt",
  type: "material",
  tileType: "dirt",
  description: "A patch of dirt.",
  level: 0,
  quantity: 0,
  maxQuantity: 64,
  isEquipped: false,
  consumeOnUse: true,
  isMaterial: true,
  canBeCrafted: true,
  canBeUsed: true,
  sellValue: 1,
  buyValue: 2,
  range: 1,
};
