import { Item } from "../../types/index.js";

export const emptyItem: Item = {
  name: "Empty",
  type: "none",
  description: "An empty slot.",
  level: 0,
  quantity: 0,
  maxQuantity: 0,
  isEquipped: false,
  consumeOnUse: false,
  isMaterial: false,
  canBeCrafted: false,
  canBeUsed: false,
  sellValue: 0,
  buyValue: 0,
  range: 0,
};

export const bronzePickaxe: Item = {
  name: "Bronze Pickaxe",
  type: "tool",
  toolType: "pickaxe",
  attackDamage: 1,
  toolDamage: 5,
  description: "A sturdy bronze pickaxe for mining.",
  level: 1,
  quantity: 1,
  maxQuantity: 1,
  isEquipped: true,
  consumeOnUse: false,
  isMaterial: true,
  canBeCrafted: false,
  canBeUsed: false,
  sellValue: 0,
  buyValue: 0,
  range: 1,
};

export const bronzeAxe: Item = {
  name: "Bronze Axe",
  type: "tool",
  toolType: "axe",
  attackDamage: 1,
  toolDamage: 5,
  description: "A sturdy bronze axe for chopping wood.",
  level: 1,
  quantity: 1,
  maxQuantity: 1,
  isEquipped: true,
  consumeOnUse: false,
  isMaterial: true,
  canBeCrafted: false,
  canBeUsed: false,
  sellValue: 0,
  buyValue: 0,
  range: 1,
};

export const bronzeRake: Item = {
  name: "Bronze Rake",
  type: "tool",
  toolType: "rake",
  attackDamage: 1,
  toolDamage: 0,
  description: "A bronze rake for tilling soil.",
  level: 1,
  quantity: 1,
  maxQuantity: 1,
  isEquipped: false,
  consumeOnUse: false,
  isMaterial: true,
  canBeCrafted: false,
  canBeUsed: false,
  sellValue: 0,
  buyValue: 0,
  range: 5,
};

export const bucketOfWater: Item = {
  name: "Bucket of Water",
  type: "tool",
  toolType: "bucket",
  filledWith:"water",
  attackDamage: 0,
  toolDamage: 0,
  description: "A bucket filled with water.",
  level: 1,
  quantity: 1,
  maxQuantity: 1,
  isEquipped: false,
  consumeOnUse: true,
  isMaterial: false,
  canBeCrafted: false,
  canBeUsed: true,
  sellValue: 0,
  buyValue: 0,
  range: 1,
}